import { NextResponse } from 'next/server';

export async function GET() {
  const productCategories = [
    {
      category: 'Energieopslag (Diensten)',
      icon: 'BatteryIcon',
      products: [
        {
          name: 'Sluxer Home 16 kWh',
          capacity: '16 kWh',
          power: '7.68 kW max',
          warranty: '10 jaar',
          price: '€0,00',
          popular: true,
          badgeEnabled: true,
          badgeText: 'Gratis installatie',
          features: ['94% efficiëntie', '≥ 8000 cycli', 'CAN/RS485/Bluetooth'],
          image: 'https://i.imgur.com/SLuA5sC.png',
          link: 'https://www.sluxer.com/products/home-16-kwh?Monta%C5%BC=Brak+%2823%25+VAT%29',
          details: [
            'Capaciteit: 314Ah | 16 kWh',
            'Configuratie: 1P16S',
            'Efficiëntie: 94%',
            'Nominale spanning: 51.2 V',
            'Aanbevolen werkspanning: 48.0–54.4 V',
            'Werkbereik (max): 42.0–58.4 V',
            'Levensduur: ≥ 8000 cycli',
            'Max. laadstroom: 150 A',
            'Max. laadvermogen: 7.68 kW',
            'Max. ontlaadstroom: 150 A',
            'Max. ontlaadvermogen: 7.68 kW',
            'Communicatie: CAN / RS485 / Bluetooth',
            'Afmetingen (HxBxD): 817 × 412 × 267 mm',
            'Gewicht: 113 kg',
            'Producent: Sluxer Energy',
            'Leveringstermijn: 10 werkdagen',
            'Bedrijfstemperaturen: Laden 0–40°C, Ontladen −5–40°C',
          ],
        },
        {
          name: 'Sluxer Home 32 kWh',
          capacity: '32.154 kWh',
          power: '9.728 kW max',
          warranty: '10 jaar',
          price: '€0,00',
          popular: true,
          badgeEnabled: true,
          extraBadge: 'Gratis installatie',
          features: ['94% efficiëntie', '≥ 8000 cycli', 'CAN/RS485/Bluetooth'],
          image: 'https://i.imgur.com/s6sx6aX.png',
          link: 'https://www.sluxer.com/products/home-32-kwh?Monta%C5%BC=Brak+%2823%25+VAT%29',
          details: [
            'Capaciteit: 628Ah | 32.154 kWh',
            'Configuratie: 2P16S',
            'Efficiëntie: 94%',
            'Nominale spanning: 51.2 V',
            'Aanbevolen werkspanning: 48.0–54.4 V',
            'Werkbereik (max): 42.0–58.4 V',
            'Levensduur: ≥ 8000 cycli',
            'Max. laadstroom: 190 A',
            'Max. laadvermogen: 9.728 kW',
            'Max. ontlaadstroom: 190 A',
            'Max. ontlaadvermogen: 9.728 kW',
            'Communicatie: CAN / RS485 / Bluetooth',
            'Afmetingen (HxBxD): 829 × 800 × 280 mm',
            'Gewicht: 210 kg',
            'Producent: Sluxer Energy',
            'Leveringstermijn: 10 werkdagen',
            'Bedrijfstemperaturen: Laden 0–40°C, Ontladen −5–40°C',
          ],
        },
      ],
    },
    {
      category: 'Inverters (Diensten)',
      icon: 'ZapIcon',
      products: [
        {
          name: 'Hoymiles HIT-10L-G3 Hybride Omvormer 10 kW',
          capacity: '10 kW',
          power: 'Driefasig (laagspanningsbatterij)',
          warranty: '12 jaar',
          price: '€0,00',
          popular: true,
          features: ['Hybride', '4 MPPT (20 A)', 'EMS-modus', 'S-Miles Cloud monitoring'],
          image: 'https://i.imgur.com/L28G8BI.png',
          link: 'https://allegro.pl/oferta/inwerter-hoymiles-hit-10l-g3-trojfazowy-niskonapieciowy-falownik-10kw-17773467389?srsltid=AfmBOooyyu9fzjfCoXEKCatlTmdgVe0-6hRZZH6wJMheCUO3xM1FEQRb',
          details: [
            '3-fase hybride omvormer',
            '4 MPPT met 20 A ingang',
            'EMS: eigen verbruik, economisch, nood, peak shaving, tijdstarief',
            'Parallel plaatsing tot 10 units',
            'Ongebalanceerde fasebelasting mogelijk tot 50% per fase',
            'S-Miles Cloud beheer en monitoring',
            'Ondersteuning voor laagspanningsbatterijsystemen',
          ],
        },
        {
          name: 'Hoymiles HIT-20L-G3 Hybride Omvormer 20 kW',
          capacity: '20 kW',
          power: 'Driefasig (laagspanningsbatterij)',
          warranty: '12 jaar',
          price: '€0,00',
          popular: true,
          features: ['Hybride', '4 MPPT (20 A)', 'EMS-modus', 'Parallel tot 10'],
          image: 'https://i.imgur.com/HBRbYQS.png',
          link: 'https://panele-sloneczne.com/product/hoymiles-falownik-hybrydowy-hit-20l-g3-3-fazowy-niskonapieciowy/',
          details: [
            '3-fase hybride omvormer',
            '4 MPPT met 20 A ingang',
            'EMS: peak shaving en tijdstarief',
            'Parallel tot 10 omvormers',
            'Ultralichte constructie voor eenvoudige installatie',
            'Ingebouwde meter met bypass tot 50 A',
          ],
        },
        {
          name: 'DEYE SUN-8K-SG05LP3-EU Hybride Omvormer 8 kW',
          capacity: '8 kW',
          power: 'Driefasig',
          warranty: '12 jaar',
          price: '€0,00',
          popular: true,
          features: ['Hybride AC/DC', 'UPS functie', 'Smart load'],
          image: 'https://i.imgur.com/bRFgxVj.png',
          link: 'https://allegro.pl/oferta/falownik-hybrydowy-deye-sun-8k-sg05lp3-eu-sm2-3f-8kw-3f-nowa-wersja-17857775610?srsltid=AfmBOooB_8m2QRPQuSutZpieF2c2yQZqO08_-iNIpuImT8CDzo8TcaU-',
          details: [
            'Model: SUN-8K-SG05LP3-EU',
            '3-fase hybride omvormer',
            'Ondersteuning voor noodstroom (UPS)',
            'Hoge efficiëntie en stille werking',
          ],
        },
        {
          name: 'DEYE SUN-10K-SG05LP3-EU Hybride Omvormer 10 kW',
          capacity: '10 kW',
          power: 'Driefasig',
          warranty: '12 jaar',
          price: '€0,00',
          popular: true,
          features: ['Hybride', 'UPS', 'Parallel mogelijk'],
          image: 'https://i.imgur.com/bRFgxVj.png',
          link: 'https://allegro.pl/oferta/falownik-hybrydowy-deye-10-kw-sun-10k-sg05lp3-eu-3fazowy-niskonapieciowy-15136856317?srsltid=AfmBOoq53mFWi3xfn2v7kp5owTI9FING0TSGumx0Og0kg01ALOYo0zxT',
          details: [
            'Model: SUN-10K-SG05LP3-EU',
            '3-fase hybride omvormer',
            'Noodstroomondersteuning (UPS)',
            'Hoge efficiëntie en brede compatibiliteit',
          ],
        },
        {
          name: 'DEYE SUN-15K-SG05LP3-EU Hybride Omvormer 15 kW',
          capacity: '15 kW',
          power: 'Driefasig',
          warranty: '12 jaar',
          price: '€0,00',
          popular: true,
          features: ['Hybride', 'UPS', 'Smart load'],
          image: 'https://i.imgur.com/8K16zWv.png',
          link: 'https://allegro.pl/oferta/falownik-hybrydowy-inwerter-deye-sun-15k-sg05lp3-eu-sm2-15-kw-17265161801',
          details: [
            'Model: SUN-15K-SG05LP3-EU',
            '3-fase hybride omvormer',
            'Ondersteuning voor noodstroom (UPS)',
            'Hoge prestaties en betrouwbaarheid',
          ],
        },
      ],
    },
    {
      category: 'Accessoires & Installatie (Diensten)',
      icon: 'BoxIcon',
      products: [
        {
          name: 'Kabelset 50 mm² (accu-verbinding M8) — 70 cm',
          capacity: '50 mm²',
          power: '—',
          warranty: 'Werkgarantie',
          price: '€0,00',
          popular: true,
          features: ['Doorsnede 50 mm²', 'M8 eindhuls', 'Flexibele kabel'],
          image: 'https://i.imgur.com/fqygAJE.png',
          link: 'https://allegro.pl/oferta/przewod-kabel-linka-50mm2-zestaw-do-laczenia-akumulatorow-m8-2x150cm-2x1-5m-17828507695?context=29e15a33b4475cc1652b795687aa50cdc503e6506b895d61c799a44fee47bee1467aa922c1967382385023aa18283a03f80fbf11ba7348592310a563130eee0e8f38c044e092ce6e69f03bddd05d488e29cd5b376e028a793d9926ac79e48f9ce5333eb96db596152ca3eaad29f23fdc20240bc2b78d361f091015e19ac23f4e63be85e0b15aa699bc9146b07f38165e&sellerHasChanged=false&fromVariant=17828501871',
          details: [
            'Lengte: 70 cm',
            'Toepassing: verbinden van accu\'s',
            'Eindhuls: M8',
            'Materiaal: koper, flexibele kabel',
          ],
        },
        {
          name: 'Kabelset 50 mm² (accu-verbinding M8) — 150 cm',
          capacity: '50 mm²',
          power: '—',
          warranty: 'Werkgarantie',
          price: '€0,00',
          popular: true,
          features: ['Doorsnede 50 mm²', 'M8 eindhuls', 'Flexibele kabel'],
          image: 'https://i.imgur.com/fqygAJE.png',
          details: [
            'Lengte: 150 cm',
            'Toepassing: verbinden van accu\'s',
            'Eindhuls: M8',
            'Materiaal: koper, flexibele kabel',
          ],
        },
      ],
    },
  ];

  return NextResponse.json({
    success: true,
    data: productCategories,
    timestamp: new Date().toISOString(),
  });
}